### ISSUE TITLE
Delexicalized Test Set

### ISSUE THREAD

**Issue by AmitMY** [ThiagoCF05/webnlg#2]
The full test set including references was released a few months ago.
I think it would be beneficial for completeness sake to also delexicalize that data.
Reasoning:
- It is a better test set for testing referring expressions - for both seen and unseen entities.
- For systems who decouple the referring expressions generation from the sentence realization phase, this will make testing parts of systems simpler.

**Comment by ThiagoCF05** [comment]
We are finishing the review of our annotation for train and development sets. Then we are going to start to annotate the test set. You may expect it for February 2019.

**Comment by AmitMY** [comment]
Thank you, those are great news!

**Comment by AmitMY** [comment]
Thanks for completing this!

**Comment by ThiagoCF05** [comment]
Dear @AmitMY ,

As promised, the annotation of the test part of the data is already available. I am closing the issue here.

Best,
