### ISSUE TITLE
Nice Work! And here I made a Python Reader :).

### ISSUE THREAD

**Issue by zhijing-jin** [ThiagoCF05/webnlg#6]
Dear authors,

I really like your enriched WebNLG, and admire your efforts on updating it to the newest v1.5! Sometimes it is hard for people who want to gets into the datasets quickly because of the xml format. Both transforming the format into a more user-friendly Python dictionary, and cleaning the dataset needs meticulous efforts. 

I made this data reader for my own research project: [WebNLG Reader](https://github.com/zhijing-jin/WebNLG_Reader/). I wish to share this with you for better spread of your work. If there are future Python programmers who wants to use your dataset, they can easily adapt from my code and kick off projects more easily.

All in all, great work :D!

**Comment by ThiagoCF05** [comment]
Dear @zhijing-jin ,

Thank you very much for your great contribution. I added it in a "Related Projects" section in the README page.

Observation: I checked your solution and saw that you are fixing some typos ("AEGNT-1" -> "AGENT-1") and also mentioned some unaligned pairs. Once you find these issues, we would be very grateful if you could report them here so we can fix them in the corpus :-)

Once again, thank you very much!
Best regards,
Thiago

**Comment by zhijing-jin** [comment]
Hi Thiago,

Thank you for adding my Reader to your `README.md`. Also, I really appreciate that you look into my codes and find some useful parts.

For your convenience, I made 7 types of fixes and combine them in a recent [Pull Request](https://github.com/ThiagoCF05/webnlg/pull/7), so that it is convenient for you to check and use. 

I am very touched by how carefully you curated the dataset and frequently update. In case there are users with different needs, my repo just created a quick access to your dataset by (1) tokenizing the dataset for sentence-level NLG, (2) creating an easy Python reader, (3) manually fixing some sentence tokenization problems. 

Overall, great work and feel free to let me know how I can help in the future. Dank je :).

Best Regards,
Zhijing
